#!/bin/zsh
# Parse SSH config and display hosts with their details
# Output format: hostname | user@destination:port

config_file=~/.ssh/config
[[ ! -f "$config_file" ]] && exit 0

awk '
BEGIN {
    host = ""
    user = ""
    hostname = ""
    port = ""
}

/^Host / {
    # Print previous host if exists
    if (host != "" && host !~ /\*/) {
        dest = (hostname != "") ? hostname : host
        userpart = (user != "") ? user "@" : ""
        portpart = (port != "" && port != "22") ? ":" port : ""
        printf "%-20s  %s%s%s\n", host, userpart, dest, portpart
    }
    # Start new host
    host = $2
    user = ""
    hostname = ""
    port = ""
}

/^[[:space:]]+User / { user = $2 }
/^[[:space:]]+HostName / { hostname = $2 }
/^[[:space:]]+Port / { port = $2 }

END {
    # Print last host
    if (host != "" && host !~ /\*/) {
        dest = (hostname != "") ? hostname : host
        userpart = (user != "") ? user "@" : ""
        portpart = (port != "" && port != "22") ? ":" port : ""
        printf "%-20s  %s%s%s\n", host, userpart, dest, portpart
    }
}
' "$config_file"
